site_name: 'Igli Bajo <br><small><i>PhD Candidate in Finance at UZH and SFI&nbsp;</i></small>'

nav:
  - About: about/index.md
  - Research: research/index.md
  - Teaching: teaching/index.md

theme:
  name: material
  # custom_dir: overrides
  features:
    - navigation.top
    - navigation.indexes
    - toc.integrate
  favicon: assets/university-of-zurich-logo.jpg
  logo: assets/uzh_logo.png  # Update the path to your logo

markdown_extensions:
  - pymdownx.arithmatex  # Render LaTeX math
  - pymdownx.superfences  # Enhanced fenced code blocks
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight  # Syntax highlighting
  - pymdownx.inlinehilite  # Inline syntax highlighting
  - pymdownx.betterem:  # Improved emphasis
      smart_enable: all
  - pymdownx.caret  # Insertions and deletions
  - pymdownx.critic  # Critic markup
  - pymdownx.details  # Details and summary tags
  - pymdownx.emoji:  # Emoji support
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink  # Auto-linking URLs
  - pymdownx.mark  # Highlight text
  - pymdownx.smartsymbols  # Convert ASCII symbols to Unicode
  - pymdownx.tasklist:  # Task lists with checkboxes
      custom_checkbox: true
  - pymdownx.tilde  # Strikethrough text
  - toc:  # Table of contents
      permalink: "#"
  - smarty  # Smart quotes and dashes
  - admonition  # Admonition blocks
  - footnotes  # Footnotes support
  - codehilite  # Code highlighting
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - markdown.extensions.extra
  - pymdownx.extra
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - "stylesheets/extra.css"

extra_javascript:
  - "javascripts/extra.js"
  - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML